name: Deploy Mainnet

on:
  push:
    branches: [mainnet]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy Mainnet Release
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          script: pm2 deploy ecosystem.config.js mainnet_scheduler update --force
