# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run scheduler tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]
    name: Node.js ${{ matrix.node-version }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v1
    
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm/cache/files
        key: dependencies-nodejs-${{ matrix.node-version }}-package-${{ hashFiles('package.json') }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm i
      env:
        CI: true
    
    - name: Run tests
      run: npm test
      env:
        CI: true
