# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v1

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm dependencies
      run: npm install

    - name: Run build task
      run: npm run build --if-present

    - name: SSH login to server
    - uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
    
    # - name: Deploy to server
    # - run: pm2 deploy ecosystem.config.js scheduler update
    # - run: ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "pm2 deploy ecosystem.config.js scheduler update"
